version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: photos_rails_development
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/photos_rails
      - bundle:/usr/local/bundle
      - node_modules:/photos_rails/node_modules
      - ./public:/photos_rails/public
      - ./tmp:/photos_rails/tmp
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - db
      - https-portal
    environment:
      TZ: Asia/Tokyo
      DATABASE_URL: postgres://postgres:password@db/photos_rails_development
    tty: true
    env_file:
      - .env
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '3443:443'
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://host.docker.internal:3000'
volumes:
  postgres_data:
  bundle:
    driver: local
  node_modules:
    driver: local